front_page_title: Decision-making
asset_path: hallinto-assets
robots_paths:
  - '/sisallonhallinta*'
prefixes:
  en: decision-making
  fi: paatoksenteko-ja-hallinto
  sv: beslutsfattande-och-forvaltning
  ru: administration
  zxx: decision-making
